#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/var/log/sonarrannounced

# install app
[[ ! -d "/app/sonarrAnnounced/.git" ]] && \
	git clone https://github.com/l3uddz/sonarrAnnounced /app/sonarrannounced
	pip3.5 install -r /app/sonarrannounced/requirements.txt
	#mv /app/sonarrannounced/settings.cfg.default /app/sonarrannounced/settings.cfg

# permissions
chown -R abc:abc \
	/app

chmod 777 \
	/var/log/sonarrannounced
